name: Keep my Duolingo streak

on:
  schedule:
    - cron: '0 12 * * *' # Runs automatically every day
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install required network tools
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Execute Duolingo Streak Protector
        env:
          DUOLINGO_USERNAME: ${{ secrets.DUOLINGO_USERNAME }}
          DUOLINGO_PASSWORD: ${{ secrets.DUOLINGO_PASSWORD }}
        run: python duolingo.py
